name: ds-example-project
channels:
- defaults
dependencies:
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2018.1.18=py36_0
- click=6.7=py36h5253387_0
- flask=0.12.2=py36hb24657c_0
- intel-openmp=2018.0.0=hc7b2577_8
- itsdangerous=0.24=py36h93cc618_1
- jinja2=2.10=py36ha16c418_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- markupsafe=1.0=py36hd9260cd_1
- mkl=2018.0.1=h19d6760_4
- ncurses=6.0=h9df7e31_2
- nose=1.3.7=py36hcdf7029_2
- numpy=1.14.0=py36h3dfced4_1
- openssl=1.0.2n=hb7f436b_0
- pip=9.0.1=py36h6c6f9ce_4
- python=3.6.4=hc3d631a_1
- readline=7.0=ha6073c6_4
- setuptools=38.5.1=py36_0
- sqlite=3.22.0=h1bed415_0
- tk=8.6.7=hc745277_3
- werkzeug=0.14.1=py36_0
- wheel=0.30.0=py36hfd4bba0_1
- xz=5.2.3=h55aa19d_2
- zlib=1.2.11=ha838bed_2
prefix: /opt/conda/envs/ds-example-project